// Geodesy checks against pyproj (PROJ 9) reference values; see tools/gen_geo_vectors.py.
#include "mini_test.hpp"
#include "tbo/geo.hpp"

using namespace tbo::geo;

namespace {
struct Vec {
  double lat, lon, h;
  int zone;
  double E, N, X, Y, Z;
};
// Generated by pyproj: EPSG:4326 -> EPSG:326xx/327xx and EPSG:4979 -> EPSG:4978.
const Vec kVectors[] = {
    {55.8100000000, 37.4620000000, 168.4000, 37, 403612.500820, 6186003.633680, 2851536.332999, 2185057.575748, 5252722.963012},
    {55.8000000000, 37.3900000000, 174.3000, 37, 399074.769310, 6184993.410454, 2855014.242783, 2182033.745676, 5252102.092671},
    {55.8050000000, 37.4200000000, 170.0000, 37, 400967.880341, 6185506.494694, 2853503.727681, 2183247.063258, 5252411.431325},
    {55.7558000000, 37.6173000000, 150.0000, 37, 413224.137659, 6179766.953877, 2849547.795986, 2195818.206444, 5249314.274438},
    {60.0000000000, 30.0000000000, 10.0000, 36, 332705.178876, 6655205.483635, 2768778.120959, 1598554.793462, 5500485.794193},
    {-33.9000000000, 18.4000000000, 5.0000, 34, 259583.221660, 6245888.045441, 5028527.724301, 1672768.532410, -3537248.136631},
};
}  // namespace

TEST_CASE("geodetic -> ECEF matches pyproj to 1 mm") {
  for (const auto& v : kVectors) {
    const Ecef p = geodeticToEcef({v.lat, v.lon, v.h});
    CHECK_NEAR(p.x, v.X, 1e-3);
    CHECK_NEAR(p.y, v.Y, 1e-3);
    CHECK_NEAR(p.z, v.Z, 1e-3);
  }
}

TEST_CASE("ECEF -> geodetic round trip below 1e-9 deg / 1 mm") {
  for (const auto& v : kVectors) {
    const Geodetic g = ecefToGeodetic({v.X, v.Y, v.Z});
    CHECK_NEAR(g.lat_deg, v.lat, 1e-9);
    CHECK_NEAR(g.lon_deg, v.lon, 1e-9);
    CHECK_NEAR(g.h, v.h, 1e-3);
  }
}

TEST_CASE("UTM forward matches pyproj to 1 mm, inverse round trips") {
  for (const auto& v : kVectors) {
    const Utm u = geodeticToUtm(v.lat, v.lon);
    CHECK(u.zone == v.zone);
    CHECK(u.north == (v.lat >= 0));
    CHECK_NEAR(u.easting, v.E, 1e-3);
    CHECK_NEAR(u.northing, v.N, 1e-3);
    const Geodetic g = utmToGeodetic(u);
    CHECK_NEAR(g.lat_deg, v.lat, 1e-8);
    CHECK_NEAR(g.lon_deg, v.lon, 1e-8);
  }
}

TEST_CASE("ENU tangent plane matches PROJ topocentric") {
  // pyproj pipeline cart+topocentric, origin = first vector, point = second vector.
  const LocalCartesian lc({55.81, 37.462, 168.4});
  const Enu p = lc.forward({55.80, 37.39, 174.3});
  CHECK_NEAR(p.e, -4515.572905, 1e-3);
  CHECK_NEAR(p.n, -1111.066322, 1e-3);
  CHECK_NEAR(p.u, 4.208493, 1e-3);
  const Geodetic back = lc.reverse(p);
  CHECK_NEAR(back.lat_deg, 55.80, 1e-9);
  CHECK_NEAR(back.lon_deg, 37.39, 1e-9);
  CHECK_NEAR(back.h, 174.3, 1e-3);
}

TEST_CASE("UTM differences and ENU differ by ~100 m on this route (frame matters)") {
  const Utm a = geodeticToUtm(55.81, 37.462), b = geodeticToUtm(55.80, 37.39);
  const LocalCartesian lc({55.81, 37.462, 168.4});
  const Enu p = lc.forward({55.80, 37.39, 174.3});
  CHECK(std::fabs((b.northing - a.northing) - p.n) > 50.0);
}
